repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3.8
        args: ["--line-length=88", "--safe"]
        files: \.py$
