# Generated by Django 4.2.17 on 2025-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(default="", null=True)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dob", models.DateField()),
                (
                    "prefered_language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("tamil", "Tamil"),
                            ("telugu", "Telugu"),
                            ("hindi", "Hindi"),
                        ],
                        default="english",
                        max_length=15,
                    ),
                ),
                (
                    "prefered_payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("net_banking", "Net Banking"),
                            ("upi", "Upi"),
                            ("wallet", "Wallet"),
                            ("cash_on_delivery", "Cash On Delivery"),
                        ],
                        default="cash_on_delivery",
                        max_length=25,
                    ),
                ),
                ("total_spent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_order_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("admin", "Admin"),
                            ("restaurant_owner", "Restaurant Owner"),
                            ("delivery_partner", "Delivery Partner"),
                        ],
                        default="customer",
                        max_length=30,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non Binary"),
                            ("prefer_not_to_say", "Prefer Not To Say"),
                        ],
                        default="prefer_not_to_say",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(default="", max_length=100, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.TextField()),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "user_address_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("office", "Office"),
                            ("hotel", "Hotel"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_addresses",
                        to="users.address",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_addresses",
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "db_table": "user_addresses",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="users.user",
            ),
        ),
    ]
